theme: jekyll-theme-slate
title: Vanessa Rivera-Qui\tilde nones,Ph.D. <br> Freelance Data Scientist 
description: Mathematics Ph.D. with a passion for telling stories through numbers using mathematical models, data science, science communication, and education. 
