theme: jekyll-theme-slate
title: Vanessa Rivera-Quinones, Ph.D. <br> Data Scientist 
description: Mathematics Ph.D. with a passion for telling stories through numbers using mathematical models, data science, science communication, and education. 
