# Theme by David Freeman: flexible-jekyll

title: Vanessa Rivera-Quinones <br> Data Scientist 
description: > # this means to ignore newlines until "baseurl:"
  Mathematics Ph.D. with a passion for telling stories through numbers using mathematical models, data science, 
  science communication, and education. 

permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Vanessa Rivera-Quinones, PhD # add your name
author-img: vriveraq_photo.jpg # add your photo
about-author: Applied mathematician with a passion for telling stories through numbers using mathematical models, data science, 
  science communication, and education.  # add description
social-twitter: MissVRiveraQ # add your Twitter handle
#social-facebook: # add your Facebook handle 
social-github: vriveraq # add your Github handle
social-linkedin: vriveraq # add your Linkedin handle
social-email: vrivera9021@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
